### ISSUE TITLE
System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'

### ISSUE THREAD

**Issue by Ademnn** [RenCloud/scs-sdk-plugin#110] opened 2022-12-13 21:15 UTC
Am trying to use your skd in my project but usually I get error "System.IndexOutOfRangeException: 'Index was outside the bounds of the array.'" What's about? How to fix it?

**Comment by MJRLegends** [comment] 2023-01-11 20:21
I have gotta this error a few times, look like the stacktrace for this error is 

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SCSSdkClient.SCSSdkConvert.GetFloat()
   at SCSSdkClient.SCSSdkConvert.GetTrailer()
   at SCSSdkClient.SCSSdkConvert.GetTrailers()
   at SCSSdkClient.SCSSdkConvert.Convert(Byte[] structureDataBytes)
   at SCSSdkClient.SharedMemory.Update[T]()
   at SCSSdkClient.SCSSdkTelemetry._updateTimer_Elapsed(Object sender)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

And from my testing seems to be upon loading the client using the SCSSdkClient upon windows startup, im getting old data which existing in a messed up way and still in the shared memory since shutdown doesnt mean 100% shutdown anymore on windows

**Comment by RenCloud** [comment] 2023-01-23 18:44
Thanks for reporting this. Also thanks for giving some testing infos and the stack trace. I'm aware of a similar bug when brakepoints are used. However, in normal "production" thet shouldn't be the case. 

I have some Ideas thet I will try to test the next few days. Though the exception didn't happened for me to this day it may need some iterations to fix it or I find a way to reproduce it.

**Comment by MJRLegends** [comment] 2023-01-23 19:26
Let me know if you need anymore testing/debug information or any more information overall, i will be happy to help

**Comment by jorensanbar** [comment] 2023-01-23 19:50
Has no sense.

length = 64
data[] = 32768
i = 52
_offset (21600) + i = 21652

And still, data[] is out of range with that offset...

This happens to me only and exclusively when the game is closed.

![imagen](https://user-images.githubusercontent.com/25260359/214135187-be4e27fe-cd2c-4032-8778-07a55d298796.png)

**Comment by jorensanbar** [comment] 2023-01-23 19:56
The error occurs when the offset exceeds the data[]

data[] = 32768
_offset = 32752
i = 32

_offset + 1 = 32784

Then you got a OutOfBounds data[32784]

You can catch with a if

`for (var i = 0; i < length; i++) {

                if ((_offset + i) <= _data.Length) //Avoid an OutOfBounds
                    ret[i] = _data[_offset + i];
            }`

![imagen](https://user-images.githubusercontent.com/25260359/214136223-7a8ffa84-4fb1-4799-a4f4-c8713e9eba54.png)

**Comment by RenCloud** [comment] 2023-01-23 22:19
That's a possible way to avoid the problem, but not to fix the issue. I would like to try to fix/look into that first before I only avoid it. The issue is that the array is shorter than expected, the questions here are why and does it matter or can we ignore that. 

Interesting there would be, if the data is in the same order/has the same offset as normal. Or in other words, is the available data still usable as usual (the already converted data is as expected).

**Comment by jorensanbar** [comment] 2023-01-23 22:57
Right, that just hides the problem, we have to see if the other methods make a large or smaller offset than is really necessary by leaving these Bytes out of the final Offset (64).

**Comment by RenCloud** [comment] 2023-01-28 17:50
Ok, I think I identified the problem. Seems to be a race condition... The timer seems to start another thread in any case. That means, even if another is still running. Most of the time, that is the expected behavior for that kind of timer. However, due to this, the offset is in rare situations modified by another thread, which then can lead to the reported `OutOfBoundsException`.

This probably happens because, wrongly for multithreading, I initialize the converting code as class in `SharedMemory.cs`... Most of the time it doesn't matter, but when a call needs too much time, it can then lead to the reported exception. Seems to be the same bug for debugging.

The fix for this shouldn't be too difficult. I try to get it done today or tomorrow.

**Comment by MJRLegends** [comment] 2023-02-15 10:54
I've been running the changes from https://github.com/RenCloud/scs-sdk-plugin/pull/112 for a week or so now, and i can confirm as expected it does fully solve this issue without any side effects.

Thank you for fixing

**Comment by RenCloud** [comment] 2023-02-16 05:17
That's nice too hear. Thanks for testing it.

**Comment by RenCloud** [comment] 2023-09-21 15:12
Finally released as V. 1.12.1 and was already tested in dev.

**Closed by RenCloud** 2023-09-21 15:12 UTC
Labels: bug
